# Automatically sync repo to upstream twice per day

# .github/workflows/sync.yml

name: Merge upstream branches
on:
  schedule:
    - cron:  '* */12 * * *'
    
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'STREAM-RS'
          git config --global user.email 'STREAM-RS@users.noreply.github.com'
          git pull --unshallow
          git remote add upstream https://github.com/BrandonSmithJ/MDN
          git fetch upstream
          git checkout master
          git merge --no-edit upstream/master
          git push origin master
